spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password: 
      driver-class-name: org.h2.Driver
       
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    
logging:
  level:
    root: debug
    '[org.hibernate]': debug