spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password: 
      driver-class-name: org.h2.Driver
       
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.jdbc.batch_size]': 50
      '[hibernate.show_sql]': true    
      '[hibernate.format_sql]': true    
      '[hibernate.highlight_sql]': true    
    
logging:
  level:
    root: info
    '[org.hibernate.SQL]': info
    '[org.hibernate.orm.jdbc.bind]': trace
